/**
* =============================================================================
* Federal University of Rio Grande do Sul (UFRGS)
* Connectionist Artificial Intelligence Laboratory (LIAC)
* Jorge C. Chamby Diaz - jccdiaz@inf.ufrgs.br
* =============================================================================
* Copyright (c) 2017 Jorge C. Chamby Diaz, jchambyd at gmail dot com
* 
* Permission is hereby granted, free of charge, to any person obtaining a copy 
* of this software and associated documentation files (the "Software"), to deal 
* in the Software without restriction, including without limitation the rights 
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell 
* copies of the Software, and to permit persons to whom the Software is 
* furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in 
* all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
* SOFTWARE.
* =============================================================================
*/

package liac.igmn.gui;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import liac.igmn.core.IGMN;
import liac.igmn.evaluation.ConfusionMatrix;
import liac.igmn.loader.DataLoader;
import liac.igmn.loader.Dataset;
import liac.igmn.util.MatrixUtil;
import liac.preprocessing.DatasetFilter;
import org.ejml.simple.SimpleMatrix;
import weka.core.Instances;

/**
 *
 * @author liac01
 */
public class Interface extends javax.swing.JFrame {

	private IGMN poIGMN;
	private int pnNumInstances;
	private int pnCurrent;
	private SimpleMatrix paDataSet;
	private String psPath;
	private Dataset pdsDataset;
	private int pnNumFeatures;
	private int pnNumClasses;
	
	/**
	 * Creates new form Interface
	 */
	public Interface() {
		initComponents();
		this.mxStateControls(1);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txnNumIns = new javax.swing.JTextField();
        cmbLearn = new javax.swing.JButton();
        txnTau = new javax.swing.JTextField();
        txnDelta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbInicialize = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txnTotIns = new javax.swing.JTextField();
        cmbExit = new javax.swing.JButton();
        cmbVisualize = new javax.swing.JButton();
        cmbReset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cmbLoad = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txnNumInstances = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txcName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DSC-IGMN");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txnNumIns.setText("1");

        cmbLearn.setText("Learn");
        cmbLearn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmbLearnMousePressed(evt);
            }
        });

        txnTau.setText("0.001");

        txnDelta.setText("0.5");

        jLabel1.setText("Tau:");

        jLabel2.setText("Delta:");

        jLabel3.setText("# Instances");

        cmbInicialize.setText("Inicialize");
        cmbInicialize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmbInicializeMousePressed(evt);
            }
        });

        jLabel4.setText("Total Instances:");

        txnTotIns.setText("0");
        txnTotIns.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txnTotIns))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txnDelta, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                            .addComponent(txnTau)
                            .addComponent(txnNumIns))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbInicialize, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(cmbLearn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txnTau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txnDelta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cmbInicialize))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txnNumIns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cmbLearn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txnTotIns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cmbExit.setText("Exit");
        cmbExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmbExitMousePressed(evt);
            }
        });

        cmbVisualize.setText("Visualize");
        cmbVisualize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmbVisualizeMousePressed(evt);
            }
        });

        cmbReset.setText("Reset");
        cmbReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmbResetMousePressed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cmbLoad.setText("Load Dataset");
        cmbLoad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmbLoadMousePressed(evt);
            }
        });

        jLabel5.setText("DataSet");

        jLabel6.setText("# Instances:");

        txnNumInstances.setEnabled(false);

        jLabel12.setText("Name:");

        txcName.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addComponent(cmbLoad))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txcName, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txnNumInstances, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txcName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txnNumInstances, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cmbReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbVisualize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbExit)
                    .addComponent(cmbVisualize)
                    .addComponent(cmbReset))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbExitMousePressed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cmbExitMousePressed

    private void cmbLearnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbLearnMousePressed
        // TODO add your handling code here:
		this.mxLearn();
    }//GEN-LAST:event_cmbLearnMousePressed

    private void cmbInicializeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbInicializeMousePressed
        // TODO add your handling code here:
		this.mxInicialize();
    }//GEN-LAST:event_cmbInicializeMousePressed

    private void cmbVisualizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbVisualizeMousePressed
        // TODO add your handling code here:
		this.mxVisualize();
    }//GEN-LAST:event_cmbVisualizeMousePressed

    private void cmbResetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbResetMousePressed
        // TODO add your handling code here:
		this.mxReset();
    }//GEN-LAST:event_cmbResetMousePressed

    private void cmbLoadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbLoadMousePressed
        // TODO add your handling code here:
        this.mxLoadInstances();
    }//GEN-LAST:event_cmbLoadMousePressed

	private void mxStateControls(int tnState)
	{
		this.txnNumIns.setEnabled(false);
		this.txnDelta.setEnabled(false);
		this.txnTau.setEnabled(false);
		this.cmbInicialize.setEnabled(false);
		this.cmbLearn.setEnabled(false);
		this.cmbVisualize.setEnabled(false);
		this.cmbReset.setEnabled(false);
		
		switch(tnState)
		{
			case 1://Inicialize
				this.txnDelta.setEnabled(true);
				this.txnTau.setEnabled(true);
				this.cmbInicialize.setEnabled(true);
				this.cmbInicialize.requestFocus();
				break;
			case 2://Test
				this.txnNumIns.setEnabled(true);
				this.cmbLearn.setEnabled(true);
				this.cmbLearn.requestFocus();
				this.cmbReset.setEnabled(true);
				break;
			case 3://Visualize
				this.txnNumIns.setEnabled(true);
				this.cmbLearn.setEnabled(true);
				this.cmbVisualize.setEnabled(true);
				this.cmbVisualize.requestFocus();
				this.cmbReset.setEnabled(true);
				break;
			default:
				break;
		}
	}
	
	private void mxLoadInstances()
	{
		boolean llOk = this.mxLoadFile();
        
        if(llOk)
        {   
            this.mxLoadDataSet();
		}
	}
	
	private boolean mxLoadFile()
    {
        JFileChooser loFileChooser = new JFileChooser();
        File loFileSelected;
        int lnResult;
              
        loFileChooser.setCurrentDirectory(new File("data/test"));
        loFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        loFileChooser.setMultiSelectionEnabled(false);
        loFileChooser.setAcceptAllFileFilterUsed(false);

        //Filter extensions
        loFileChooser.addChoosableFileFilter(new FileNameExtensionFilter("*.arff", "arff"));
        loFileChooser.addChoosableFileFilter(new FileNameExtensionFilter("*.txt", "txt"));
		
        lnResult = loFileChooser.showOpenDialog(this);

        if (lnResult == JFileChooser.APPROVE_OPTION) 
        {
            loFileSelected = loFileChooser.getSelectedFile();
            this.psPath = loFileSelected.getAbsolutePath();
            this.txcName.setText(loFileSelected.getName());
            return true;
        }
        
        return false;        
    }
	
	public void mxLoadDataSet()
	{
		String lsExtention;
        try
        {
            //Get extension to file
            lsExtention = this.mxGetExtension(this.psPath);

            switch(lsExtention)
            {
                case "txt":
                    this.pdsDataset = DataLoader.loadTXT(this.psPath);
                    DatasetFilter.normalize(this.pdsDataset);
                    this.pnNumFeatures = this.pdsDataset.getInputSize();
                    this.pnNumClasses = this.pdsDataset.getNumClasses();
					this.txnNumInstances.setText("" + this.pdsDataset.getDataset().numCols());
                    break;
                case "arff":
                    this.pdsDataset = DataLoader.loadARFF(this.psPath);
                    DatasetFilter.normalize(this.pdsDataset);
                    this.pnNumFeatures = this.pdsDataset.getInputSize();
                    this.pnNumClasses = this.pdsDataset.getNumClasses();
					this.txnNumInstances.setText("" + this.pdsDataset.getDataset().numCols());
                    break;
                default:
                    break;
            }
        }
        catch(Exception e)
        {
            
        }
	}
	
	private void mxLearn()
	{	
		int lnNumTest = Integer.parseInt(this.txnNumIns.getText());
		ConfusionMatrix loConfusionMatrix = new ConfusionMatrix(this.pdsDataset.getClassesNames());
	
		if(this.pnNumInstances < lnNumTest + this.pnCurrent)
		{
			JOptionPane.showMessageDialog(null, "Instances for testing max.: " + (this.pnNumInstances - this.pnCurrent));
            this.txnNumIns.requestFocus();
            return;
		}
		
		for(int i = 0; i < lnNumTest; i++)
        {
			SimpleMatrix loInstance = this.paDataSet.extractVector(false, this.pnCurrent + i);
            SimpleMatrix loInput = loInstance.extractMatrix(0, this.pnNumFeatures, 0, SimpleMatrix.END);
            SimpleMatrix loTarget = loInstance.extractMatrix(this.pnNumFeatures, this.pnNumClasses + this.pnNumFeatures, 0, SimpleMatrix.END);
            
            SimpleMatrix y = this.poIGMN.classify(loInput);
                        
            int tInd = MatrixUtil.maxElementIndex(loTarget);
            int yInd = MatrixUtil.maxElementIndex(y);

            loConfusionMatrix.addPrediction(tInd, yInd); 

            this.poIGMN.train(loInstance);
		}
		
		System.out.println(loConfusionMatrix.toString("*** Matriz de Confusão ***"));	
        System.out.printf("Total de Instâncias: %d\n", (int) loConfusionMatrix.total());
        System.out.printf("Acurácia: %.1f%%\n", loConfusionMatrix.accuracy() * 100);
        System.out.printf("Erro: %.1f%%\n", loConfusionMatrix.errorRate() * 100);

        for(int i = 0; i < loConfusionMatrix.size(); i++)
        {
            double accuracy = loConfusionMatrix.accuracy(i) * 100;
            System.out.printf("classe: %s - acurácia: %.1f%%\n", loConfusionMatrix.className(i), accuracy);
        }
		
		//SimpleMatrix laDataTest = this.paDataSet.extractMatrix( 0, this.paDataSet.numRows(), this.pnCurrent, this.pnCurrent + lnNumTest);
		
		//this.poIGMN.train(laDataTest);
		
		this.pnCurrent += lnNumTest;
		
		this.txnTotIns.setText("" + this.pnCurrent);
		
		this.mxStateControls(3);
	}	
	
	private void mxInicialize()
	{
		int i = 0;
		double lnTau = Double.parseDouble(this.txnTau.getText());
        double lnDelta = Double.parseDouble(this.txnDelta.getText());
		
		Instances loInstances = this.pdsDataset.getWekaDataset();
        this.paDataSet = MatrixUtil.instancesToMatrix(loInstances);
		
		SimpleMatrix loRange = this.pdsDataset.getDataRange();
		
		this.poIGMN = new IGMN(loRange, lnTau, lnDelta);
				
		this.pnNumInstances = this.paDataSet.numCols();
		this.pnCurrent = 0;		
		this.mxStateControls(2);
	}
	
	private void mxVisualize()
	{
		int lnNumTest = Integer.parseInt(this.txnNumIns.getText());
		SimpleMatrix loData = this.paDataSet.extractMatrix( 0, this.paDataSet.numRows(), this.pnCurrent - lnNumTest, this.pnCurrent);
		
		Visualize loVisualize = new Visualize(this, true, this.poIGMN, this.poIGMN, loData, this.pnNumFeatures);
        loVisualize.setVisible(true);
		
		this.mxStateControls(2);
	}
	
	private void mxReset()
	{
		this.mxStateControls(1);
		this.txnNumIns.setText("1");
		this.txnTotIns.setText("0");
		this.pnNumInstances = 0;
		this.pnCurrent = 0;
	}
	
	private String mxGetExtension(String tsPath)
    {
        for (int i = tsPath.length() - 1; i > 0; i--) 
        {
            if(tsPath.charAt(i) == '.')
                return tsPath.substring(i + 1);
        }
        return "";
    }
	
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Interface().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmbExit;
    private javax.swing.JButton cmbInicialize;
    private javax.swing.JButton cmbLearn;
    private javax.swing.JButton cmbLoad;
    private javax.swing.JButton cmbReset;
    private javax.swing.JButton cmbVisualize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txcName;
    private javax.swing.JTextField txnDelta;
    private javax.swing.JTextField txnNumIns;
    private javax.swing.JTextField txnNumInstances;
    private javax.swing.JTextField txnTau;
    private javax.swing.JTextField txnTotIns;
    // End of variables declaration//GEN-END:variables
}
